# Generated by Django 4.1.3 on 2022-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
