# Generated by Django 4.1.3 on 2022-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_youtube_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
