# Generated by Django 4.1.3 on 2022-11-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
