# Generated by Django 4.1.3 on 2022-11-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_youtube_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='youtube_code',
            new_name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='content',
            name='youtube_thumbnail',
        ),
    ]
