# Generated by Django 4.1.3 on 2022-12-13 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0009_rename_like_count_content_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
