# Generated by Django 4.1.3 on 2022-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_thumnail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='youtube_ids_count',
            field=models.IntegerField(null=True),
        ),
    ]
